name: node-red-updated
services:
  app:
    image: nodered/node-red:3.1.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: host
    ports:
      - target: 1880
        published: "1880"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: node-red-updated
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Node-RED is a programming tool for wiring together hardware devices, APIs and online services in new and interesting ways.  It provides a browser-based editor that makes it easy to wire together flows using the wide range of nodes in the palette that can be deployed to its runtime in a single-click.
  tagline:
    en_us: Low-code programming for event-driven applications
  developer: ""
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/node-red.png
  thumbnail: ""
  title:
    en_us: Node-RED Updated
  category: BigBearCasaOS
  port_map: "1880"
