version: "3.7"

services:
  app:
    image: adguard/adguardhome:v0.107.35
    restart: unless-stopped
    ports:
      # plain DNS
      - target: 53
        published: 53
        protocol: tcp
      - target: 53
        published: 53
        protocol: udp
      # DHCP Server
      - target: 67
        published: 67
        protocol: udp
      - target: 68
        published: 68
        protocol: tcp
      - target: 68
        published: 68
        protocol: udp
      # HTTP
      - target: 7200
        published: 80
        protocol: tcp
      - target: 7200
        published: 80
        protocol: udp
      # Setup
      - target: 7201
        published: 3000
        protocol: tcp
      - target: 7201
        published: 3000
        protocol: udp
      # DNS-over-HTTPS
      - target: 443
        published: 443
        protocol: tcp
      - target: 443
        published: 443
        protocol: udp
      # DNS-over-TLS
      - target: 853
        published: 853
        protocol: tcp
      # DNS-over-QUIC
      - target: 784
        published: 784
        protocol: udp
      - target: 853
        published: 853
        protocol: udp
      - target: 8853
        published: 8853
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data/work
        target: /opt/adguardhome/work
      - type: bind
        source: /DATA/AppData/$AppID/data/conf
        target: /opt/adguardhome/conf

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Network-wide ads & trackers blocking DNS server
  tagline:
    en_us: Network-wide ads & trackers blocking DNS server
  developer: ""
  author: BigBearTechWorld
  icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/adguard-home.png?raw=true
  thumbnail: https://github.com/walkxcode/dashboard-icons/blob/main/png/adguard-home.png?raw=true
  title:
    en_us: Adguard Home
  category: Network
  port_map: "7200"
