name: flame
services:
  app:
    image: pawelmalak/flame
    environment:
      PASSWORD: casaos
    restart: unless-stopped
    ports:
      - target: 5005
        published: "5005"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /app/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us:
      Flame is self-hosted startpage for your server. Its design is inspired
      (heavily) by SUI. Flame is very easy to setup and use. With built-in
      editors, it allows you to setup your very own application hub in no time -
      no file editing necessary.
  tagline:
    en_us:
      Flame is self-hosted startpage for your server. Its design is inspired
      (heavily) by SUI. Flame is very easy to setup and use. With built-in
      editors, it allows you to setup your very own application hub in no time -
      no file editing necessary.
  developer: ""
  author: BigBearCommunity
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/flame.png
  thumbnail: https://github.com/pawelmalak/flame/blob/master/.github/themes.png
  title:
    en_us: Flame
  category: BigBearCasaOS
  port_map: "7200"
