# Configuration for speedtest-tracker setup

# Name of the big-bear-speedtest-tracker application
name: big-bear-speedtest-tracker

# Service definitions for the big-bear-speedtest-tracker application
services:
  # Service name: app
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=casaos
      - DB_PASSWORD=casaos
      - TZ=America/Chicago
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/DATA/AppData/$AppID/config:/config"
      - "/DATA/AppData/$AppID/web:/etc/ssl/web"
    image: "ghcr.io/alexjustesen/speedtest-tracker:v0.12.1"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mariadb:10
    restart: always
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=casaos
      - MARIADB_PASSWORD=casaos
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - "/DATA/AppData/$AppID/mysql:/var/lib/mysql"

# CasaOS specific configuration
x-casaos:
  # Supported CPU architectures for the application
  architectures:
    - amd64
    - arm
    - arm64
  # Main service of the application
  main: speedtest-tracker
  description:
    # Description in English
    en_us: A Docker image to check your internet speed using Ookla's Speedtest service. Build using Laravel and the Speedtest CLI.
  tagline:
    # Short description or tagline in English
    en_us: Speedtest Tracker
  # Developer's name or identifier
  developer: "alexjustesen"
  # Author of this configuration
  author: BigBearTechWorld
  # Icon for the application
  icon: https://github.com/alexjustesen/speedtest-tracker/blob/main/public/img/speedtest-tracker-icon.png?raw=true
  # Thumbnail image (currently empty)
  thumbnail: ""
  title:
    # Title in English
    en_us: Speedtest Tracker
  # Application category
  category: BigBearCasaOS
  # Port mapping information
  port_map: "8080"
