# Configuration for the big-bear-rally setup

# Name of the big-bear-rallly application
name: big-bear-rallly

# Definition of services required for the big-bear-rallly application
services:
  # Main application service definition
  big-bear-rallly:
    container_name: big-bear-rallly # The name for the container instance of this service
    image: lukevella/rallly:3.7.0 # Docker image to be used for creating the container
    restart: unless-stopped # Policy to restart the container unless manually stopped
    environment: # Environment variables passed to the container for configuration
      # Database connection URL
      - DATABASE_URL=postgres://rallly:f87c7126-f816-47ef-9193-2e5eec763fcd@big-bear-rallly-db/big-bear-rallly
      - SECRET_PASSWORD=0f6f292d-c78c-4709-920d-e3b6361eb5b5 # Secret password for application security
      # URL for the frontend to use, replace [YOUR_CASAOS_IP] with your actual CasaOS IP
      - NEXT_PUBLIC_BASE_URL=http://[YOUR_CASAOS_IP]:3000
      - NOREPLY_EMAIL=noreply@example.com # Email used for sending no-reply messages
      - SUPPORT_EMAIL=support@example.com # Support contact email
      # SMTP configuration for sending emails, to be filled with your SMTP server details
      - SMTP_HOST=[YOUR_CASAOS_IP]
      - SMTP_PORT=1025
      - SMTP_SECURE=
      - SMTP_USER=
      - SMTP_PWD=
      - SMTP_TLS_ENABLED=
      - ALLOWED_EMAILS= # Specify allowed emails if needed

    ports:
      - "3000:3000" # Maps port 3000 on the host to port 3000 on the container

    networks:
      - big_bear_rally_network # Connects the container to the specified network

    depends_on:
      big-bear-rallly-db:
        condition: service_healthy # Ensures the DB service is healthy before starting

    # CasaOS specific configurations for user interface
    x-casaos:
      envs:
        # Detailed descriptions for environment variables to display in CasaOS UI
        - container: DATABASE_URL
          description:
            en_us: "Database URL: postgres://rallly:f87c7126-f816-47ef-9193-2e5eec763fcd@big-bear-rallly-db/big-bear-rallly"
        # Additional environment variable descriptions...

  # Database service for the application
  big-bear-rallly-db:
    container_name: big-bear-rallly-db # Container name for the database service
    image: postgres:14 # PostgreSQL version 14 as the database
    restart: unless-stopped # Restart policy similar to the application service
    volumes:
      - /DATA/AppData/$AppID/postgresql:/var/lib/postgresql/data # Persistent data storage
    environment:
      - POSTGRES_PASSWORD=f87c7126-f816-47ef-9193-2e5eec763fcd # DB password
      - POSTGRES_DB=big-bear-rallly # Database name
      - POSTGRES_USER=rallly # Database user
    networks:
      - big_bear_rally_network # Uses the same network as the application service
    healthcheck: # Checks if the database service is ready to accept connections
      test: ["CMD-SHELL", "pg_isready -U rallly"]
      interval: 5s
      timeout: 5s
      retries: 5

# Network definitions for the application
networks:
  big_bear_rally_network:
    driver: bridge # Uses bridge network driver

# Additional CasaOS specific configuration
x-casaos:
  architectures:
    - amd64
    - arm64 # Supported CPU architectures
  main: big-bear-rallly # Main service of the application
  description:
    en_us: Rallly is an open-source scheduling and collaboration tool designed to make organizing events and meetings easier. # Application description
  tagline:
    en_us: Rallly # Short tagline or slogan
  developer: "lukevella" # Developer or maintainer of the application
  author: BigBearTechWorld # The author of this configuration
  icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/rallly.png?raw=true # Icon URL
  thumbnail: "" # Thumbnail image URL (currently empty)
  title:
    en_us: Rallly # Title of the application in English
  category: BigBearCasaOS # Category under which the app is listed
  port_map: "3000" # Port mapping information for user reference
  tips: # Tips or instructions for the user before installation
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-rallly-to-bigbearcasaos/1012#instructions-3
