name: ntfy
services:
  app:
    image: binwiederhier/ntfy
    command:
      - serve
    environment:
      - TZ=UTC
    ports:
      - target: 80
        published: "7200"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/cache
        target: /var/cache/ntfy
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /etc/ntfy
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: ntfy (pronounced notify) is a simple HTTP-based pub-sub notification service. It allows you to send notifications to your phone or desktop via scripts from any computer, and/or using a REST API. It's infinitely flexible, and 100% free software.
  tagline:
    en_us: A simple HTTP-based pub-sub notification service
  developer: ""
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/ntfy.png
  thumbnail: https://ntfy.sh/_next/static/media/screenshot-web-3.de6f19af.png
  title:
    en_us: Ntfy.sh
  category: BigBearCasaOS
  port_map: "7200"
